# modules/home-manager/blackmatter/components/fd-limits/default.nix
#
# Per-session file-descriptor ceiling — the HM face of the fleet's "max
# headroom everywhere" FD posture (operator decision 2026-06-30).
#
# The system faces raise the HARD ceiling:
#   - Darwin: blackmatter.profiles.macos.limits (launchctl) +
#     pleme.darwin.profiles.developerResources (kern.maxfiles* sysctl)
#   - NixOS:  blackmatter.components.systemLimits (PAM + systemd + fs.nr_open)
#
# This component guarantees the interactive SOFT limit actually reaches that
# hard ceiling regardless of how the session was launched (a GUI-spawned
# shell can otherwise inherit macOS's stingy 256 soft default). It writes a
# fragment into ~/.config/shell/local.d, which the blackmatter shell engine
# (frostmourne/blzsh) sources on every interactive startup.
{
  config,
  lib,
  ...
}:
with lib; let
  cfg = config.blackmatter.components.fdLimits;
in {
  options.blackmatter.components.fdLimits = {
    enable = mkEnableOption "raise the interactive shell's open-file soft limit to the hard ceiling" // {
      default = true;
    };
  };

  config = mkIf cfg.enable {
    # Raise the soft limit to whatever the hard ceiling allows. Using
    # `$(ulimit -H -n)` keeps this self-adjusting: it always grabs the max the
    # system faces granted (2^24 today) without hardcoding the number in a
    # third place. Guarded so a sandbox with a frozen hard limit never errors
    # the shell startup.
    xdg.configFile."shell/local.d/zz-fd-limits.zsh".text = ''
      # Generated by Nix (blackmatter.components.fdLimits) — DO NOT EDIT.
      # Raise open-file soft limit to the hard ceiling (max FD headroom).
      __bm_fd_hard="$(ulimit -H -n 2>/dev/null)"
      if [ -n "$__bm_fd_hard" ]; then
        ulimit -S -n "$__bm_fd_hard" 2>/dev/null || true
      fi
      unset __bm_fd_hard
    '';
  };
}
