# modules/darwin/blackmatter/profiles/macos/dns/default.nix
{
  config,
  pkgs,
  lib,
  ...
}:
with lib; let
  cfg = config.blackmatter.profiles.macos.dns;
in {
  options = {
    blackmatter = {
      profiles = {
        macos = {
          dns = {
            enable = mkEnableOption "enable DNS configuration with dnsmasq";

            bind = mkOption {
              type = types.str;
              default = "127.0.0.1";
              description = "IP address to bind dnsmasq to";
            };

            port = mkOption {
              type = types.int;
              default = 53;
              description = "Port for dnsmasq to listen on";
            };

            cacheSize = mkOption {
              type = types.int;
              default = 1000;
              description = "DNS cache size";
            };

            upstreamServers = mkOption {
              type = types.listOf types.str;
              default = ["1.1.1.1" "8.8.8.8"];
              description = ''
                Upstream DNS servers. Overridden when `posture` is set —
                see that option for the typescape-driven path.
              '';
            };

            posture = mkOption {
              type = types.nullOr (types.submodule {
                options = {
                  label = mkOption {
                    type = types.str;
                    description = "Posture label (e.g. \"baseline\", \"nordvpn-active\").";
                  };
                  description = mkOption {
                    type = types.str;
                    default = "";
                    description = "Operator-facing description of the posture.";
                  };
                  postureId = mkOption {
                    type = types.str;
                    description = "Content-addressed BLAKE3 id (16 hex chars) — drift fingerprint.";
                  };
                  upstreamServers = mkOption {
                    type = types.listOf types.str;
                    description = "Deduplicated resolver chain: primary → secondary → absolute_floor.";
                  };
                  addresses = mkOption {
                    type = types.attrsOf types.str;
                    default = {};
                    description = "Per-domain address overrides (domain → IP).";
                  };
                  health = mkOption {
                    # Free-form attrset of probe configuration; consumed
                    # by the M2.1 oboe daemon. We don't constrain shape
                    # here so future probe types (TCP, DoT) don't force
                    # a module update.
                    type = types.attrs;
                    description = ''
                      Health probe configuration for the orchestrator
                      (oboe, M2.1). Fields:
                        - query                    (str)
                        - expect                   (str: "answer-nonempty" | "rcode-ok")
                        - intervalMs               (int)
                        - timeoutMs                (int)
                        - failuresBeforeUnhealthy  (int)
                    '';
                  };
                  fallback = mkOption {
                    type = types.attrs;
                    default = { kind = "promote-secondary"; };
                    description = ''
                      What the orchestrator does when the health probe
                      declares the primary chain unhealthy. Fields:
                        - kind   (str)
                        - label  (str, only when kind = "switch-posture")
                    '';
                  };
                };
              });
              default = null;
              example = literalExpression ''
                # Generated by `arch-synthesizer dns_posture::render_nix_attrset`.
                import ./postures/nordvpn-active.nix
              '';
              description = ''
                Optional typed DNS posture from
                `arch-synthesizer/src/dns_posture/`. When set, overrides
                `upstreamServers` with `posture.upstreamServers` and
                merges `posture.addresses` into the dnsmasq address map
                — making the rendered posture the single source of truth
                for the host's DNS resolver chain.

                The substrate refuses to render a posture with empty
                `absolute_floor`, so a non-null value here always
                guarantees DNS keeps resolving even if upstream VPN
                resolvers are unreachable.

                Source of truth: pleme-io/arch-synthesizer
                `dns_posture::DnsPosture::render_nix_attrset()`.
                Catalog (M2+): pleme-io/repo-forge
                `dns-posture-catalog.lisp`.
              '';
            };

            useNetworkTopology = mkOption {
              type = types.bool;
              default = true;
              description = ''
                Use the centralized network topology for DNS mappings.
                When enabled, all nodes and services from blackmatter.networkTopology
                will be automatically configured in dnsmasq.
                Additional mappings can still be added via addresses option.
              '';
            };

            addresses = mkOption {
              type = types.attrsOf types.str;
              default = {};
              description = ''
                Additional DNS address mappings (domain -> IP).
                These will be merged with network topology mappings if useNetworkTopology is true.
              '';
              example = {
                "app.test" = "127.0.0.1";
                "myhost.local" = "192.168.1.100";
              };
            };

            localDomains = mkOption {
              type = types.listOf types.str;
              default = ["local" "test"];
              description = "Domains that should never be forwarded upstream";
            };

            resolverDomains = mkOption {
              type = types.listOf types.str;
              default = ["local" "test"];
              description = "Domains to create macOS resolver entries for";
            };

            enableAliases = mkOption {
              type = types.bool;
              default = true;
              description = "Enable DNS management shell aliases";
            };
          };
        };
      };
    };
  };

  config = mkIf cfg.enable (let
    # When a typed posture is authored, it becomes the single source of
    # truth for the upstream chain + per-domain overrides. Otherwise
    # fall back to the operator-declared options.
    effectiveUpstreamServers =
      if cfg.posture != null
      then cfg.posture.upstreamServers
      else cfg.upstreamServers;
    postureAddresses =
      if cfg.posture != null
      then cfg.posture.addresses
      else {};
    # Sidecar JSON file the M2.1 oboe daemon will read on startup +
    # SIGHUP. Contains the full posture: health probe, fallback policy,
    # plus the chain itself. Lives at /etc/blackmatter/dns-posture.json
    # (oboe watches that path); absence means "no posture authored,
    # fallthrough to operator defaults".
    postureSidecar =
      if cfg.posture != null
      then builtins.toJSON {
        inherit (cfg.posture) label description postureId
                              upstreamServers addresses health fallback;
      }
      else null;
  in {
    # Enable dnsmasq for local DNS resolution
    services.dnsmasq = {
      enable = true;
      bind = cfg.bind;
      port = cfg.port;
      # Merge network topology addresses with custom addresses + any
      # posture-declared per-domain overrides.
      addresses = mkMerge [
        (mkIf cfg.useNetworkTopology config.blackmatter.networkTopology.dnsAddresses)
        cfg.addresses
        postureAddresses
      ];
    };

    # Create a custom dnsmasq configuration file and resolver entries.
    # When a posture is authored, also drop the typed JSON sidecar that
    # the M2.1 oboe daemon will read.
    environment.etc = mkMerge ([
      (mkIf (postureSidecar != null) {
        "blackmatter/dns-posture.json".text = postureSidecar;
      })
      {
        "dnsmasq.d/local.conf" = {
          text = ''
            # Cache settings
            cache-size=${toString cfg.cacheSize}

            ${concatMapStrings (domain: ''
              # Never forward ${domain} queries upstream
              local=/${domain}/

            '') cfg.localDomains}
            # Forward Tailscale MagicDNS queries to Tailscale's resolver
            server=/ts.net/100.100.100.100

            ${optionalString (cfg.posture != null) ''
              # dns_posture: ${cfg.posture.label} (${cfg.posture.postureId})
              # ${cfg.posture.description}
            ''}
            # Upstream DNS servers (typed posture takes precedence over
            # `upstreamServers` when `posture` is set):
            ${concatMapStrings (server: "server=${server}\n") effectiveUpstreamServers}
          '';
        };
      }
    ] ++ (map (domain: {
      "resolver/${domain}".text = ''
        nameserver ${cfg.bind}
        port ${toString cfg.port}
      '';
    }) cfg.resolverDomains));

    # Add DNS testing utilities
    environment.systemPackages = with pkgs; [
      dnsutils  # This package includes dig, host, and nslookup
    ];

    # Add helpful aliases
    programs.zsh.interactiveShellInit = mkIf (config.programs.zsh.enable && cfg.enableAliases) ''
      # DNS management aliases
      alias dns-status='sudo launchctl list | grep dnsmasq || echo "dnsmasq not running"'
      alias dns-restart='sudo launchctl kickstart -k system/org.nixos.dnsmasq'
      alias dns-test='dig @127.0.0.1 localhost'
      alias dns-flush='sudo dscacheutil -flushcache'

      # Function to set local DNS
      function set-local-dns() {
        sudo networksetup -setdnsservers Wi-Fi 127.0.0.1
        echo "DNS set to 127.0.0.1 for Wi-Fi"
      }

      # Function to reset DNS to DHCP
      function reset-dns() {
        sudo networksetup -setdnsservers Wi-Fi empty
        echo "DNS reset to DHCP for Wi-Fi"
      }
    '';

    # Point all network services at dnsmasq on activation.
    # dnsmasq forwards non-local queries to upstream servers (1.1.1.1, 8.8.8.8),
    # so internet DNS continues to work. This ensures /etc/resolver/* files
    # are actually consulted by macOS for local domain resolution.
    system.activationScripts.postActivation.text = lib.mkAfter ''
      for svc in "Wi-Fi" "Thunderbolt Bridge"; do
        /usr/sbin/networksetup -getnetworkserviceenabled "$svc" 2>/dev/null | grep -q Enabled && \
          /usr/sbin/networksetup -setdnsservers "$svc" ${cfg.bind} 2>/dev/null || true
      done
      /usr/bin/dscacheutil -flushcache 2>/dev/null || true
      /usr/bin/killall -HUP mDNSResponder 2>/dev/null || true
    '';

    # Flush DNS cache periodically to pick up topology changes
    launchd.daemons.dns-refresh = {
      command = "/usr/bin/dscacheutil -flushcache";
      serviceConfig = {
        StartInterval = 3600;
        RunAtLoad = true;
      };
    };
  });
}
